apiVersion: v1
kind: Service
metadata:
  name: pfadi-finder-midata-adapter
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: pfadi-finder-midata-adapter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfadi-finder-midata-adapter
spec:
  selector:
    matchLabels:
      app: pfadi-finder-midata-adapter
  template:
    metadata:
      labels:
        app: pfadi-finder-midata-adapter
    spec:
      containers:
        - name: pfadi-finder-midata-adapter
          image: ghcr.io/scout-ch/pfadi-finder-midata-adapter:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: pfadi-finder-midata-adapter-secrets
          env:
            - name: BASE_URL
              value: "https://db.scout.ch"
            - name: MINAGE
              value: "24"
            - name: "USE_BASIC_AUTH"
              value: "no"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-pfadifinder-midata-adapter-division-data
spec:
  schedule: "0 */24 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: refresh-data
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - http://pfadi-finder-midata-adapter.svc:3000/src/updatedivisions.php
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-pfadifinder-midata-adapter-divisions
spec:
  schedule: "0 0 */7 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: refresh-data
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - http://pfadi-finder-midata-adapter.svc:3000/src/index.php
