apiVersion: v1
kind: Secret
metadata:
  name: pfadi-finder-midata-adapter-secrets
type: Opaque
stringData:
  DATABASE_HOST: "pfadi-finder-midata-adapter-host"
  DATABASE_USER: "pfadi-finder-midata-adapter"
  DATABASE_PORT: "3306"
  DATABASE_PASSWORD: "password"
  DATABASE_DB: "pfadi-finder-midata-adapter"
  TOKEN: "hitobito-access-token"
  EXCLUDED_GROUPS: "1,2"
  AUTH_USER: "auth-user"
  AUTH_PASSWORD: "password"
