<?php

$config = [
  'BASE_URL' => $_ENV['BASE_URL'],
  'TOKEN' => $_ENV['TOKEN'],
  'DATABASE_HOST' => $_ENV['DATABASE_HOST'],
  'DATABASE_USER' => $_ENV['DATABASE_USER'],
  'DATABASE_PASSWORD' => $_ENV['DATABASE_PASSWORD'],
  'DATABASE_DB' => $_ENV['DATABASE_DB'],
  'MINAGE' => $_ENV['MINAGE']
];

define("GEOLOCATION_SWITZERLAND_NORTH_LIMIT", 47.811263);
define("GEOLOCATION_SWITZERLAND_SOUTH_LIMIT", 45.811958);
define("GEOLOCATION_SWITZERLAND_EAST_LIMIT", 10.523665);
define("GEOLOCATION_SWITZERLAND_WEST_LIMIT", 5.922318);
